site_name: My Docs
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  lenguage: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme : slate
      toggle:
         icon: material/toggle-switch
         name: Switch to light mode
      primary: teal
      accent: lime

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex: 
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      languages:
        default:
          name: Default (en)
          build: true
        en:
          name: English
          build: true
        fr:
          name: Français
          build: true
        es:
          name: Spanish
          build: true
        ca:
          name: Catalan
          build: true

copyright: |
  &copy; 2023 <a href="https://github.com" target="_blank" rel="noopener">Oihan Pintado</a>