site_name: Prueba MkDocs

repo_name: Oyanpi/Prueba_MkDocs_Oihan
repo_url: https://oyanpi.github.io/Prueba_MkDocs_Oihan/

theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  lenguage: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: cyan
      accent: indigo
    - scheme : slate
      toggle:
         icon: material/lightbulb-outline
         name: Switch to light mode
      primary: deep purple
      accent: pink

extra: 
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex: 
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins:
  - mike
  - search
  - mkdocs-video
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      languages:
        en:
          name: English
          build: true
        fr:
          name: Français
          build: true
        es:
          name: Spanish
          build: true
        ca:
          name: Catalan
          build: true
        eu:
          name: Euskera
          build: true
  - page-to-pdf

copyright: |
  &copy; 2023 <a href="https://github.com" target="_blank" rel="noopener">Oihan Pintado</a>