name: ci
on:
    push:
        branches:
            - main
            
permissions:
    contents: write
jobs:
    deploy:
        runs-on: windows-10
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                key: ${{ github.ref }}
                path: .cache
            - run: pip install mkdocs-material
            - run: mkdocs gh-deploy --force